[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
day1 = { path = "../days/day1" }
day2 = { path = "../days/day2" }
day3 = { path = "../days/day3" }
day4 = { path = "../days/day4" }
